# Generated by Django 2.2.2 on 2019-08-28 17:44

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='country_name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='usabilitySurvey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='UsabilitySurvey', editable=False, max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('usage_frequency', models.CharField(choices=[('Strongly_Disagree', 'Strongly Disagree'), ('Disagree', 'Disagree'), ('Natural', 'Natural'), ('Agree', 'Agree'), ('Strongly_Agree', 'Strongly Agree')], default=None, max_length=20, verbose_name='usage_frequency')),
                ('system_complexity', models.CharField(choices=[('Strongly_Disagree', 'Strongly Disagree'), ('Disagree', 'Disagree'), ('Natural', 'Natural'), ('Agree', 'Agree'), ('Strongly_Agree', 'Strongly Agree')], default=None, max_length=20, verbose_name='system_complexity')),
                ('usage_ease', models.CharField(choices=[('Strongly_Disagree', 'Strongly Disagree'), ('Disagree', 'Disagree'), ('Natural', 'Natural'), ('Agree', 'Agree'), ('Strongly_Agree', 'Strongly Agree')], default=None, max_length=20, verbose_name='usage_ease')),
                ('need_help', models.CharField(choices=[('Strongly_Disagree', 'Strongly Disagree'), ('Disagree', 'Disagree'), ('Natural', 'Natural'), ('Agree', 'Agree'), ('Strongly_Agree', 'Strongly Agree')], default=None, max_length=20, verbose_name='need_help')),
                ('functions_integrated', models.CharField(choices=[('Strongly_Disagree', 'Strongly Disagree'), ('Disagree', 'Disagree'), ('Natural', 'Natural'), ('Agree', 'Agree'), ('Strongly_Agree', 'Strongly Agree')], default=None, max_length=20, verbose_name='functions_integrated')),
                ('system_inconsistency', models.CharField(choices=[('Strongly_Disagree', 'Strongly Disagree'), ('Disagree', 'Disagree'), ('Natural', 'Natural'), ('Agree', 'Agree'), ('Strongly_Agree', 'Strongly Agree')], default=None, max_length=20, verbose_name='system_inconsistency')),
                ('learn_to_use', models.CharField(choices=[('Strongly_Disagree', 'Strongly Disagree'), ('Disagree', 'Disagree'), ('Natural', 'Natural'), ('Agree', 'Agree'), ('Strongly_Agree', 'Strongly Agree')], default=None, max_length=20, verbose_name='learn_to_use')),
                ('system_inconvenient', models.CharField(choices=[('Strongly_Disagree', 'Strongly Disagree'), ('Disagree', 'Disagree'), ('Natural', 'Natural'), ('Agree', 'Agree'), ('Strongly_Agree', 'Strongly Agree')], default=None, max_length=20, verbose_name='system_inconvenient')),
                ('confident_level', models.CharField(choices=[('Strongly_Disagree', 'Strongly Disagree'), ('Disagree', 'Disagree'), ('Natural', 'Natural'), ('Agree', 'Agree'), ('Strongly_Agree', 'Strongly Agree')], default=None, max_length=20, verbose_name='confident_level')),
                ('learning_before', models.CharField(choices=[('Strongly_Disagree', 'Strongly Disagree'), ('Disagree', 'Disagree'), ('Natural', 'Natural'), ('Agree', 'Agree'), ('Strongly_Agree', 'Strongly Agree')], default=None, max_length=20, verbose_name='learning_before')),
                ('comment', models.CharField(blank=True, max_length=250)),
                ('email', models.EmailField(blank=True, max_length=150)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'UsabilitySurvey',
                'db_table': 'UsabilitySurvey',
                'ordering': ['user_id'],
            },
        ),
        migrations.CreateModel(
            name='step_2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='step2', editable=False, max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('features', multiselectfield.db.fields.MultiSelectField(choices=[('Education Quality', 'Education Quality'), ('Political Insecurity', 'Political Insecurity'), ('Social Conflict', 'Social Conflict'), ('Work Opportunities', 'Work Opportunities'), ('Health care', 'Health Care'), ('Income Difference', 'Income Difference'), ('Wars & Dictatorship', 'Wars & Dictatorship'), ('Family Member Abroad', 'Family Member Abroad'), ('Cultural & Linguistic Similarities', 'Cultural & Linguistic Similarities'), ('Working Atmosphere', 'Working Atmosphere'), ('Shorter Distance', 'Shorter Distance'), ('Crime Rate', 'Crime Rate')], max_length=200)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'features',
                'db_table': 'Features',
                'ordering': ['user_id'],
            },
        ),
        migrations.CreateModel(
            name='step_1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='step1', editable=False, max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('refuse_to_disc', 'Refuse to disclose')], default=None, max_length=20, verbose_name='gender')),
                ('age', models.CharField(choices=[('under_18', 'Under 18'), ('b18_24', '18 24'), ('b25_35', '25 35'), ('b35_45', '35 45'), ('b45_55', '45 55'), ('bover_55', 'Over 55')], default=None, max_length=40, verbose_name='age')),
                ('country', django_countries.fields.CountryField(default=None, max_length=2)),
                ('imaginative', models.CharField(choices=[('Strongly_Disagree', 'Strongly Disagree'), ('Disagree', 'Disagree'), ('Natural', 'Natural'), ('Agree', 'Agree'), ('Strongly_Agree', 'Strongly Agree')], default=None, max_length=20, verbose_name='imaginative')),
                ('organized', models.CharField(choices=[('Strongly_Disagree', 'Strongly Disagree'), ('Disagree', 'Disagree'), ('Natural', 'Natural'), ('Agree', 'Agree'), ('Strongly_Agree', 'Strongly Agree')], default=None, max_length=20, verbose_name='organized')),
                ('enthusiastic', models.CharField(choices=[('Strongly_Disagree', 'Strongly Disagree'), ('Disagree', 'Disagree'), ('Natural', 'Natural'), ('Agree', 'Agree'), ('Strongly_Agree', 'Strongly Agree')], default=None, max_length=20, verbose_name='enthusiastic')),
                ('kind', models.CharField(choices=[('Strongly_Disagree', 'Strongly Disagree'), ('Disagree', 'Disagree'), ('Natural', 'Natural'), ('Agree', 'Agree'), ('Strongly_Agree', 'Strongly Agree')], default=None, max_length=20, verbose_name='kind')),
                ('calm', models.CharField(choices=[('Strongly_Disagree', 'Strongly Disagree'), ('Disagree', 'Disagree'), ('Natural', 'Natural'), ('Agree', 'Agree'), ('Strongly_Agree', 'Strongly Agree')], default=None, max_length=20, verbose_name='calm')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Personal_info',
                'db_table': 'Personal_information',
                'ordering': ['user_id'],
            },
        ),
        migrations.CreateModel(
            name='user_rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='user_rate', editable=False, max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('country_rating', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('countries_name_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thesis_app.country_name')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user_rate',
                'db_table': 'user_ratings',
                'unique_together': {('countries_name_id', 'user_id')},
            },
        ),
    ]
