# Generated by Django 2.2.2 on 2019-08-28 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thesis_app', '0002_user_result'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user_result',
            options={'verbose_name': 'user_result'},
        ),
        migrations.AlterModelTable(
            name='user_result',
            table='user_result',
        ),
    ]
