# Generated by Django 2.2.2 on 2019-09-06 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesis_app', '0005_auto_20190906_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usabilitysurvey',
            name='comment',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
