# Generated by Django 2.2.2 on 2019-07-22 12:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('thesis_app', '0011_auto_20190719_1012'),
    ]

    operations = [
        migrations.CreateModel(
            name='step_2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('features', multiselectfield.db.fields.MultiSelectField(choices=[(' Education quality', 'Education quality'), ('Political insecurity', 'Political insecurity'), ('Social_conflict', 'Social_conflict'), ('opportunities', 'opportunities'), ('Health care', 'Health care'), ('Income difference', 'Income difference'), ('Wars and Dictatorship', 'Wars and Dictatorship'), ('Family member abroad', 'Family member abroad'), ('cultural and linguistic similarities', 'cultural and linguistic similarities'), ('Working atmosphere', 'Working atmosphere'), ('Shorter Distance', 'Shorter Distance'), ('Crime rate', 'Crime rate')], max_length=55)),
                ('user_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
