# Generated by Django 2.2.2 on 2019-07-22 12:30

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('thesis_app', '0012_step_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step_2',
            name='features',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(' Education quality', 'Education quality'), ('Political insecurity', 'Political insecurity'), ('Social_conflict', 'Social_conflict'), ('opportunities', 'opportunities'), ('Health care', 'Health care'), ('Income difference', 'Income difference'), ('Wars and Dictatorship', 'Wars and Dictatorship'), ('Family member abroad', 'Family member abroad'), ('cultural and linguistic similarities', 'cultural and linguistic similarities'), ('Working atmosphere', 'Working atmosphere'), ('Shorter Distance', 'Shorter Distance'), ('Crime rate', 'Crime rate')], max_length=200),
        ),
    ]
