# Generated by Django 2.2.2 on 2019-07-22 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesis_app', '0013_auto_20190722_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='step_2',
            name='title',
            field=models.CharField(default='step2', editable=False, max_length=20),
        ),
    ]
