# Generated by Django 2.2.2 on 2019-07-22 23:30

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('thesis_app', '0014_step_2_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step_2',
            name='features',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(' Education Quality', 'Education Quality'), ('Political Insecurity', 'Political Insecurity'), ('Social Conflict', 'Social Conflict'), ('Work Opportunities', 'Work Opportunities'), ('Health care', 'Health Care'), ('Income Difference', 'Income Difference'), ('Wars & Dictatorship', 'Wars & Dictatorship'), ('Family Member Abroad', 'Family Member Abroad'), ('Cultural & Linguistic Similarities', 'Cultural & Linguistic Similarities'), ('Working Atmosphere', 'Working Atmosphere'), ('Shorter Distance', 'Shorter Distance'), ('Crime Rate', 'Crime Rate')], max_length=200),
        ),
    ]
