# Generated by Django 2.2.2 on 2019-07-24 10:10

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('thesis_app', '0020_auto_20190724_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step_1',
            name='country',
            field=django_countries.fields.CountryField(default=None, max_length=2),
        ),
    ]
