# Generated by Django 2.2.2 on 2019-07-27 13:46

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('thesis_app', '0023_auto_20190724_1033'),
    ]

    operations = [
        migrations.CreateModel(
            name='countries_name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='countries_name', editable=False, max_length=20)),
                ('countries', django_countries.fields.CountryField(max_length=2)),
            ],
            options={
                'verbose_name': ['title'],
            },
        ),
        migrations.CreateModel(
            name='user_rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='user_rate', editable=False, max_length=20)),
                ('country_rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('countries_name_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='thesis_app.countries_name')),
                ('user_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='current_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': ['title'],
            },
        ),
    ]
