# Generated by Django 2.2.2 on 2019-07-27 14:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesis_app', '0024_countries_name_user_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_rate',
            name='country_rating',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
