# Generated by Django 2.2.2 on 2019-07-27 15:52

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('thesis_app', '0026_countries_name_country_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='step_3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='step3', editable=False, max_length=20)),
                ('countries', django_countries.fields.CountryField(default=None, max_length=2)),
                ('country_rate', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('user_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='current_user', to=settings.AUTH_USER_MODEL)),
                ('user_rate', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': ['title'],
                'ordering': ['country_rate'],
            },
        ),
        migrations.RemoveField(
            model_name='user_rate',
            name='countries_name_id',
        ),
        migrations.RemoveField(
            model_name='user_rate',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='countries_name',
        ),
        migrations.DeleteModel(
            name='user_rate',
        ),
    ]
