# Generated by Django 2.2.2 on 2019-07-27 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thesis_app', '0027_auto_20190727_1552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='step_3',
            name='user_id',
        ),
    ]
