# Generated by Django 2.2.2 on 2019-07-28 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thesis_app', '0029_step_3_user_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='step_3',
            options={'ordering': ['country_rate'], 'verbose_name': 'step_3'},
        ),
    ]
