# Generated by Django 2.2.2 on 2019-07-29 14:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('thesis_app', '0034_auto_20190729_1427'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='user_rate',
            unique_together={('countries_name_id', 'user_id')},
        ),
    ]
