# Generated by Django 2.2.2 on 2019-07-31 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thesis_app', '0036_auto_20190729_1714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country_name',
            name='title',
        ),
    ]
