# Generated by Django 2.2.2 on 2019-08-02 11:50

from django.db import migrations
import likert_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('thesis_app', '0037_remove_country_name_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_rate',
            name='country_rating',
            field=likert_field.models.LikertField(blank=True, null=True),
        ),
    ]
