# Generated by Django 2.2.2 on 2019-08-02 17:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thesis_app', '0038_auto_20190802_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_rate',
            name='countries_name_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thesis_app.country_name'),
        ),
        migrations.AlterField(
            model_name='user_rate',
            name='country_rating',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
