# Generated by Django 2.2.2 on 2019-08-03 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thesis_app', '0043_book'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
