# Generated by Django 2.2.2 on 2019-08-05 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thesis_app', '0044_delete_book'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country_name',
            options={},
        ),
        migrations.AlterModelOptions(
            name='step_2',
            options={'ordering': ['user_id'], 'verbose_name': 'step_2'},
        ),
        migrations.AlterModelTable(
            name='country_name',
            table='Countries',
        ),
        migrations.AlterModelTable(
            name='step_1',
            table='Personal_information',
        ),
        migrations.AlterModelTable(
            name='step_2',
            table='Features',
        ),
        migrations.AlterModelTable(
            name='user_rate',
            table='user_ratings',
        ),
    ]
