# Generated by Django 2.2.2 on 2019-08-08 17:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('thesis_app', '0045_auto_20190805_1123'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='step_1',
            options={'ordering': ['user_id'], 'verbose_name': 'Personal_info'},
        ),
        migrations.AlterModelOptions(
            name='step_2',
            options={'ordering': ['user_id'], 'verbose_name': 'features'},
        ),
        migrations.AlterField(
            model_name='step_1',
            name='age',
            field=models.CharField(choices=[('Under 18', 'under_18'), ('18 24', 'b18_24'), ('25 35', 'b25_35'), ('35 45', 'b35_45'), ('45 55', 'b45_55'), ('Over 55', 'bover_55')], default=None, max_length=40, verbose_name='age'),
        ),
        migrations.AlterField(
            model_name='step_1',
            name='calm',
            field=models.CharField(choices=[('Strongly Disagree', 'Strongly_Disagree'), ('Disagree', 'Disagree'), ('Natural', 'Natural'), ('Agree', 'Agree'), ('Strongly Agree', 'Strongly_Agree')], default=None, max_length=20, verbose_name='calm'),
        ),
        migrations.AlterField(
            model_name='step_1',
            name='enthusiastic',
            field=models.CharField(choices=[('Strongly Disagree', 'Strongly_Disagree'), ('Disagree', 'Disagree'), ('Natural', 'Natural'), ('Agree', 'Agree'), ('Strongly Agree', 'Strongly_Agree')], default=None, max_length=20, verbose_name='enthusiastic'),
        ),
        migrations.AlterField(
            model_name='step_1',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Refuse to disclose', 'refuse_to_disc')], default=None, max_length=20, verbose_name='gender'),
        ),
        migrations.AlterField(
            model_name='step_1',
            name='imaginative',
            field=models.CharField(choices=[('Strongly Disagree', 'Strongly_Disagree'), ('Disagree', 'Disagree'), ('Natural', 'Natural'), ('Agree', 'Agree'), ('Strongly Agree', 'Strongly_Agree')], default=None, max_length=20, verbose_name='imaginative'),
        ),
        migrations.AlterField(
            model_name='step_1',
            name='kind',
            field=models.CharField(choices=[('Strongly Disagree', 'Strongly_Disagree'), ('Disagree', 'Disagree'), ('Natural', 'Natural'), ('Agree', 'Agree'), ('Strongly Agree', 'Strongly_Agree')], default=None, max_length=20, verbose_name='kind'),
        ),
        migrations.AlterField(
            model_name='step_1',
            name='organized',
            field=models.CharField(choices=[('Strongly Disagree', 'Strongly_Disagree'), ('Disagree', 'Disagree'), ('Natural', 'Natural'), ('Agree', 'Agree'), ('Strongly Agree', 'Strongly_Agree')], default=None, max_length=20, verbose_name='organized'),
        ),
        migrations.CreateModel(
            name='UsabilitySurvey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='UsabilitySurvey', editable=False, max_length=20)),
                ('usage_frequency', models.CharField(choices=[('Strongly Disagree', 'Strongly_Disagree'), ('Disagree', 'Disagree'), ('Natural', 'Natural'), ('Agree', 'Agree'), ('Strongly Agree', 'Strongly_Agree')], default=None, max_length=20, verbose_name='usage_frequency')),
                ('system_complexity', models.CharField(choices=[('Strongly Disagree', 'Strongly_Disagree'), ('Disagree', 'Disagree'), ('Natural', 'Natural'), ('Agree', 'Agree'), ('Strongly Agree', 'Strongly_Agree')], default=None, max_length=20, verbose_name='system_complexity')),
                ('usage_ease', models.CharField(choices=[('Strongly Disagree', 'Strongly_Disagree'), ('Disagree', 'Disagree'), ('Natural', 'Natural'), ('Agree', 'Agree'), ('Strongly Agree', 'Strongly_Agree')], default=None, max_length=20, verbose_name='usage_ease')),
                ('need_help', models.CharField(choices=[('Strongly Disagree', 'Strongly_Disagree'), ('Disagree', 'Disagree'), ('Natural', 'Natural'), ('Agree', 'Agree'), ('Strongly Agree', 'Strongly_Agree')], default=None, max_length=20, verbose_name='need_help')),
                ('functions_integrated', models.CharField(choices=[('Strongly Disagree', 'Strongly_Disagree'), ('Disagree', 'Disagree'), ('Natural', 'Natural'), ('Agree', 'Agree'), ('Strongly Agree', 'Strongly_Agree')], default=None, max_length=20, verbose_name='functions_integrated')),
                ('system_inconsistency', models.CharField(choices=[('Strongly Disagree', 'Strongly_Disagree'), ('Disagree', 'Disagree'), ('Natural', 'Natural'), ('Agree', 'Agree'), ('Strongly Agree', 'Strongly_Agree')], default=None, max_length=20, verbose_name='system_inconsistency')),
                ('learn_to_use', models.CharField(choices=[('Strongly Disagree', 'Strongly_Disagree'), ('Disagree', 'Disagree'), ('Natural', 'Natural'), ('Agree', 'Agree'), ('Strongly Agree', 'Strongly_Agree')], default=None, max_length=20, verbose_name='learn_to_use')),
                ('system_inconvenient', models.CharField(choices=[('Strongly Disagree', 'Strongly_Disagree'), ('Disagree', 'Disagree'), ('Natural', 'Natural'), ('Agree', 'Agree'), ('Strongly Agree', 'Strongly_Agree')], default=None, max_length=20, verbose_name='system_inconvenient')),
                ('confident_level', models.CharField(choices=[('Strongly Disagree', 'Strongly_Disagree'), ('Disagree', 'Disagree'), ('Natural', 'Natural'), ('Agree', 'Agree'), ('Strongly Agree', 'Strongly_Agree')], default=None, max_length=20, verbose_name='confident_level')),
                ('learning_before', models.CharField(choices=[('Strongly Disagree', 'Strongly_Disagree'), ('Disagree', 'Disagree'), ('Natural', 'Natural'), ('Agree', 'Agree'), ('Strongly Agree', 'Strongly_Agree')], default=None, max_length=20, verbose_name='learning_before')),
                ('comment', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('user_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'UsabilitySurvey',
                'db_table': 'UsabilitySurvey',
                'ordering': ['user_id'],
            },
        ),
    ]
