# Generated by Django 2.2.2 on 2019-08-18 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesis_app', '0046_auto_20190808_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usabilitysurvey',
            name='comment',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='usabilitysurvey',
            name='email',
            field=models.EmailField(blank=True, max_length=200),
        ),
    ]
