# Generated by Django 2.2.2 on 2019-08-18 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesis_app', '0047_auto_20190818_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usabilitysurvey',
            name='comment',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='usabilitysurvey',
            name='email',
            field=models.EmailField(blank=True, max_length=500),
        ),
    ]
