# Generated by Django 2.2.2 on 2019-08-24 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesis_app', '0051_auto_20190824_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_rate',
            name='title',
            field=models.CharField(default='user_rate', editable=False, max_length=20),
        ),
    ]
