# Generated by Django 2.2.2 on 2019-08-24 12:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thesis_app', '0053_auto_20190824_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step_1',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='step_2',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usabilitysurvey',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user_rate',
            name='countries_name_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thesis_app.country_name'),
        ),
    ]
