# Generated by Django 2.2.2 on 2019-08-24 18:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('thesis_app', '0055_auto_20190824_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='usabilitysurvey',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
