# Generated by Django 2.2.2 on 2019-08-24 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesis_app', '0057_auto_20190824_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='country_name',
            name='flag',
            field=models.ImageField(default=1, upload_to='countries_flag'),
            preserve_default=False,
        ),
    ]
