# Generated by Django 2.2.2 on 2019-08-25 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesis_app', '0058_country_name_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country_name',
            name='country_name',
            field=models.CharField(max_length=50),
        ),
    ]
