# Generated by Django 2.2.2 on 2019-07-18 11:13

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('thesis_app', '0007_auto_20190718_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step_1',
            name='age',
            field=models.CharField(choices=[('under_18', 'under_18'), ('18_24', '18_24'), ('25_35', '25_35'), ('35_45', '35_45'), ('45_55', '45_55'), ('Over_55', 'Over_55')], default='under_18', max_length=40, verbose_name='age'),
        ),
        migrations.AlterField(
            model_name='step_1',
            name='country',
            field=django_countries.fields.CountryField(default='New Zealand', max_length=2),
        ),
    ]
