# Generated by Django 2.2.2 on 2019-07-18 17:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thesis_app', '0008_auto_20190718_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step_1',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
