# Generated by Django 2.2.2 on 2019-07-19 10:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thesis_app', '0009_auto_20190718_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step_1',
            name='user_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
